### ISSUE TITLE
Credit for the ACM Panel drawing

### ISSUE THREAD

**Issue by Mongoose556** [Tractorou24/F14-Tomcat-Home-Cockpit#1]
Hello! 

I am the original author of the ACM panel drawing. Would you be able to credit me? :)
Regards, Mongoose

**Comment by Tractorou24** [comment]
Hello !

That's pushed in the master branch ! Thank you for your work, it was useful !
Unfortunately, I don't have time to continue this project but would like to...

**Comment by Mongoose556** [comment]
Hi there! thanks for that, I remember posting it on the ED forum!  I was
really surprised to see it again and glad you found it useful 😊

Regards, Mongoose
